version: "3.7"

services:

  themes:
    build:
      context: ./themes
      dockerfile: Dockerfile
    volumes:
      - ./themes:/home/node/app
    profiles:
      - "test"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev --http-relative-path=/auth
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - ./themes/build/codeflix-catalog:/opt/keycloak/themes/keycloak
  
  test:
    build: ./tests
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test
    volumes:
      - ./tests:/home/node/app
    networks:
      - app-network
    profiles:
      - "test"

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    networks:
      - app-network
    profiles:
      - "test"


networks:
  app-network:
    