version: "3.7"

services:

  themes:
    build:
      context: ./themes
      dockerfile: Dockerfile
    volumes:
      - ./themes:/home/node/app
    profiles:
      - "test"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev --http-relative-path=/auth --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - ./tests/imports:/opt/keycloak/data/import
      - ./themes/build/codeflix-catalog:/opt/keycloak/themes/codeflix-catalog
    networks: 
      default:
        aliases: 
          - app.test

  test:
    build: ./tests
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test
    volumes:
      - ./tests:/home/node/app
    networks: 
        - default
    profiles:
      - "test"

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    networks: 
        - default
    profiles:
      - "test"


networks: 
  default:
    driver: bridge    